[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
h2e_fee_claimer = "BMC4fwHFriXWz34dPgXaBm7yd8MopGh9u47cyMpAKWia"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "wallets/payer.json"

[scripts]
test = "true"
